spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    consul:
      # 服务发现配置
      discovery:
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: gateway-server
    gateway:
      discovery:
        locator:
          enabled: true #启用基于服务发现的路由定义定位器
          lower-case-service-id: true
      default-filters:
      routes: #配置路由路径
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultfallback # 只有该id下的服务会降级
        - id: account-server
          uri: lb://account-server
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultfallback # 只有该id下的服务会降级
  redis:
    host: xxxxxxx
    port: 123
    password: xxx

server:
  port: 8080

# 此时可以设置hystrix超时时间（毫秒），默认只有2秒
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 30000
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/favicon.ico"
management:
  endpoints:
    web:
      exposure:
        include: "*"