spring:
  application:
    name: account-server
  profiles:
    active: dev
  cloud:
    consul:
      # 服务发现配置
      discovery:
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        service-name: account-server
    stream:
      binders: #绑定器
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                addresses: 106.55.159.234
                port: 5672
                username: admin
                password: admin
                virtual-host: /
      bindings:
        systemLogOutput: #系统日志生产者配置
          destination: 4a.systemlog #exchange名称，交换模式默认是topic
          binder: defaultRabbit
          content-type: application/json

    loadbalancer:
      ribbon:
        enabled: false
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
